name: Build and Deploy

on:
  push:
    branches:
      - main  # 빌드를 자동화할 브랜치를 지정합니다. 필요에 따라 변경할 수 있습니다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@main

    - name: Node.js 설치
      uses: actions/setup-node@main
      with:
        node-version: 14

    - name: 의존성 설치
      run: npm install

    - name: 빌드
      run: npm run build  # 빌드 스크립트가 `npm run build`인 경우입니다. 필요에 따라 변경할 수 있습니다.

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: main  # 배포할 브랜치를 지정합니다. 필요에 따라 변경할 수 있습니다.
        folder: docs  # 빌드된 파일이 위치한 폴더를 지정합니다. 필요에 따라 변경할 수 있습니다.        
        